### ISSUE TITLE
If the network connection is faster than the drive speed, memory fills up.

### ISSUE THREAD

**Issue by cmosig** [cmosig/sentle#1]
It seems like that when networking and processing are fast enough and the drive where the results are saved becomes the bottleneck, dask continues to download and process chunks without waiting for the disk. This fills up memory and crashes the process at some point. 

Current "fix": reduce the number of workers when initiating sentle until memory does not fill up anymore. 

Ideal fix: tell dask somehow to wait for disk I/O.

**Comment by davemlz** [comment]
WHAT
