### ISSUE TITLE
Cloud masking error

### ISSUE THREAD

**Issue by Sonicious** [cmosig/sentle#5]
In case `S2_cloud_classification=False` the setting of `S2_apply_cloud_mask=True` gives an error.

Maybe a warning is a possibility to cover this.

**Comment by cmosig** [comment]
need to change logic here: https://github.com/cmosig/sentle/blob/d4465a657e5d5ed4c2a210721c5fcb2a7ae7b216/sentle/sentle.py#L649C1-L649C32
